let dicoComments = new Map([
    ["Specification", new Map([
        [0, new Map([["subcontractor", true],["levelRecommended", null]])],
        [1, new Map([["subcontractor", true],["levelRecommended", null]])],
        [2, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [3, new Map([["subcontractor", false],["levelRecommended", null]])],
        [4, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [5, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [6, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [7, new Map([["subcontractor", true],["levelRecommended", null]])],
        [8, new Map([["subcontractor", true],["levelRecommended", null]])],
        [9, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [10, new Map([["subcontractor", true],["levelRecommended", null]])],
        [11, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [12, new Map([["subcontractor", true],["levelRecommended", null]])],
        [13, new Map([["subcontractor", true],["levelRecommended", null]])],
        [14, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [15, new Map([["subcontractor", true],["levelRecommended", null]])],
        [16, new Map([["subcontractor", true],["levelRecommended", null]])],
        [17, new Map([["subcontractor", true],["levelRecommended", null]])]
    ])],
    ["Design", new Map([
        [0, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [1, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],[2, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [3, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [4, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [5, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [6, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [7, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [8, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [9, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [10, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [11, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [12, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [13, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [14, new Map([["subcontractor", false],["levelRecommended", null]])],
        [15, new Map([["subcontractor", false],["levelRecommended", new Set(['3'])]])],
        [16, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [17, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [18, new Map([["subcontractor", false],["levelRecommended", null]])],
        [19, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [20, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [21, new Map([["subcontractor", false],["levelRecommended", null]])],
        [22, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [23, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [24, new Map([["subcontractor", true],["levelRecommended", null]])],
        [25, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [26, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3'])]])],
        [27, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [28, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [29, new Map([["subcontractor", false],["levelRecommended", null]])],
        [30, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])]
    ])],
    ["Manufacturing of board - Subassembly", new Map([
        [0, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [1, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [2, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [3, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [4, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [5, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [6, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [7, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [8, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [9, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [10, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [11, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [12, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [13, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [14, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [15, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [16, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [17, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [18, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [19, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [20, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [21, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [22, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [23, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [24, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [25, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [26, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [27, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [28, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [29, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [30, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [31, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [32, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [33, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [34, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [35, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [36, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [37, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [38, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [39, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [40, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [41, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [42, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],[43, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [44, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],[45, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [46, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [47, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [48, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [49, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [50, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [51, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [52, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [53, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])]
    ])],
    ["Integration into equipment", new Map([
        [0, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [1, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],[2, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [3, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [4, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [5, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [6, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [7, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [8, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [9, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [10, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [11, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [12, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],[13, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [14, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [15, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [16, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [17, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [18, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [19, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [20, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [21, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [22, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [23, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [24, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [25, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [26, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [27, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [28, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [29, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [30, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [31, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [32, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [33, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [34, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [35, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [36, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [37, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [38, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [39, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [40, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [41, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [42, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [43, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [44, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [45, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [46, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [47, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])],
        [48, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [49, new Map([["subcontractor", true],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [50, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [51, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [52, new Map([["subcontractor", true],["levelRecommended", new Set(['2', '3', '4'])]])],
        [53, new Map([["subcontractor", true],["levelRecommended", new Set(['3', '4'])]])]
    ])],
    ["Integration into system", new Map([
        [0, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [1, new Map([["subcontractor", false],["levelRecommended", new Set(['2', '3', '4'])]])],
        [2, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [3, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [4, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [5, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [6, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [7, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [8, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [9, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [10, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [11, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [12, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [13, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [14, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [15, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [16, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [17, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [18, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [19, new Map([["subcontractor", false],["levelRecommended", new Set(['2', '3', '4'])]])],
        [20, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [21, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [22, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [23, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [24, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [25, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [26, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [27, new Map([["subcontractor", false],["levelRecommended", new Set(['1', '2', '3', '4'])]])],[28, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [29, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [30, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [31, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [32, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [33, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [34, new Map([["subcontractor", false],["levelRecommended", new Set(['1', '2', '3', '4'])]])],
        [35, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])]
    ])],
    ["Operation and Maintenance", new Map([
        [0, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [1, new Map([["subcontractor", true],["levelRecommended", null]])],
        [2, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [3, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [4, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [5, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [6, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [7, new Map([["subcontractor", false],["levelRecommended", null]])],
        [8, new Map([["subcontractor", false],["levelRecommended", new Set(['3', '4'])]])],
        [9, new Map([["subcontractor", false],["levelRecommended", null]])],
        [10, new Map([["subcontractor", false],["levelRecommended", null]])],
        [11, new Map([["subcontractor", false],["levelRecommended", null]])],
        [12, new Map([["subcontractor", false],["levelRecommended", null]])],
        [13, new Map([["subcontractor", false],["levelRecommended", null]])],
        [14, new Map([["subcontractor", false],["levelRecommended", null]])],
        [15, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [16, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [17, new Map([["subcontractor", false],["levelRecommended", null]])],
        [18, new Map([["subcontractor", false],["levelRecommended", null]])],
        [19, new Map([["subcontractor", false],["levelRecommended", null]])],
        [20, new Map([["subcontractor", false],["levelRecommended", null]])],
        [21, new Map([["subcontractor", false],["levelRecommended", null]])],
        [22, new Map([["subcontractor", false],["levelRecommended", null]])],
        [23, new Map([["subcontractor", false],["levelRecommended", null]])],
        [24, new Map([["subcontractor", false],["levelRecommended", null]])],
        [25, new Map([["subcontractor", false],["levelRecommended", null]])],
        [26, new Map([["subcontractor", false],["levelRecommended", null]])],
        [27, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])],
        [28, new Map([["subcontractor", false],["levelRecommended", new Set(['4'])]])]
    ])],
    ["Support Activities", new Map([
        [0, new Map([["subcontractor", true],["levelRecommended", null]])],
        [1, new Map([["subcontractor", true],["levelRecommended", null]])],
        [2, new Map([["subcontractor", true],["levelRecommended", null]])],
        [3, new Map([["subcontractor", true],["levelRecommended", null]])],
        [4, new Map([["subcontractor", true],["levelRecommended", null]])],
        [5, new Map([["subcontractor", true],["levelRecommended", null]])],
        [6, new Map([["subcontractor", true],["levelRecommended", null]])],
        [7, new Map([["subcontractor", true],["levelRecommended", null]])],
        [8, new Map([["subcontractor", true],["levelRecommended", null]])],
        [9, new Map([["subcontractor", true],["levelRecommended", null]])],
        [10, new Map([["subcontractor", true],["levelRecommended", null]])],
        [11, new Map([["subcontractor", true],["levelRecommended", null]])],
        [12, new Map([["subcontractor", false],["levelRecommended", null]])],
        [13, new Map([["subcontractor", false],["levelRecommended", null]])],
        [14, new Map([["subcontractor", false],["levelRecommended", null]])],
        [15, new Map([["subcontractor", false],["levelRecommended", null]])],
        [16, new Map([["subcontractor", false],["levelRecommended", null]])],
        [17, new Map([["subcontractor", false],["levelRecommended", null]])],
        [18, new Map([["subcontractor", false],["levelRecommended", null]])],
        [19, new Map([["subcontractor", false],["levelRecommended", null]])],
        [20, new Map([["subcontractor", false],["levelRecommended", null]])],
        [21, new Map([["subcontractor", false],["levelRecommended", null]])],
        [22, new Map([["subcontractor", false],["levelRecommended", null]])],
        [23, new Map([["subcontractor", false],["levelRecommended", null]])],
        [24, new Map([["subcontractor", false],["levelRecommended", null]])],
        [25, new Map([["subcontractor", false],["levelRecommended", null]])],
        [26, new Map([["subcontractor", false],["levelRecommended", null]])],
        [27, new Map([["subcontractor", false],["levelRecommended", null]])]
    ])]
])