# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  install:
    - requirements: readthedocs_requirements.txt

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx 02_NRPMHandbook/"


# Build documentation in the 02_NRPMHandbook/ directory with Sphinx
sphinx:
  configuration: 02_NRPMHandbook/conf.py
  builder: html
  fail_on_warning: false


