# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NRPM digital handbook
author: Matrisk | Airbus Defence & Space
logo: _static/images/reliabilityspace_logo_vector.png
copyright: "2022"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# LaTeX settings
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

html:
  use_multitoc_numbering: true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: _static/images/favicon.ico
  extra_navbar: |
        <div>
            <img src="/_static/images/logo_matrisk.png" alt="Matrisk logo" style="width:40%;height:40%;">
            <img src="/_static/images/logo_airbus.png" alt="Airbus logo" style="width:50%;height:50%;margin-left:10px;">
        </div>
  announcement              : "️This is the review version v0.1.0 of the digital handbook. It is delivered as part of milestone 2 🚀"
  # announcement              : "️⚠ This digital handbook is currently under development! Content may change unexpectedly!⚠"

# Information about where the book exists on the web
repository:
  url                       : https://github.com/paulremo/NRPMHandbook  # Online location of your book
  path_to_book              : 02_NRPMHandbook  # Optional path to your book, relative to the repository root
  branch                    : main 
 
 
# modifications of sphinx config
sphinx:
  config:
    # modifications of thebe config (change of the repo URL to the interactivity repo)
    thebe_config:
      repository_url        : https://github.com/paulremo/NRPMInteractivity/v0.1.0
      repository_branch     : python
    # modifications of bibtex reference style
    bibtex_default_style    : plain
    bibtex_reference_style  : label
    execution_show_tb       : True
    execution_timeout       : 60
    # turn off jupyter notebook execution
    jupyter_execute_notebooks: "off" 
# The following is currently not possible, because it overwrites the Jupyter Book html_theme_options. There is currently no way to add this option without overwriting.
#    html_theme_options      : 
#      search_bar_text       : "Search handbook..."
  extra_extensions: 
    - sphinx_multitoc_numbering # fix, because use_multitoc_numbering doesn't get forwarded to sphinx properly by jupyter book
  
    


# deactivate mybinder button and activate thebe button
launch_buttons:
  binderhub_url             : ""
  thebe                     : true