# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NRPM Digital handbook
author: Matrisk | Airbus Defence & Space
logo: pictures/reliabilityspace_logo_vector.png
copyright: "2022"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# LaTeX settings
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

html:
  use_multitoc_numbering: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: _static/images/favicon.ico
  extra_navbar: |
        <div>
            <img src="/_static/images/logo_matrisk.png" alt="Matrisk logo" style="width:40%;height:40%;">
            <img src="/_static/images/logo_airbus.png" alt="Airbus logo" style="width:50%;height:50%;margin-left:10px;">
        </div>

# Information about where the book exists on the web
repository:
  url                       : https://github.com/paulremo/NRPMHandbook  # Online location of your book
  path_to_book              : 02_NRPMHandbook  # Optional path to your book, relative to the repository root
  branch                    : main 
 
 
# modifications of sphinx config
sphinx:
  config:
    # modifications of thebe config (change of the repo URL to the interactivity repo)
    thebe_config:
      repository_url        : https://github.com/paulremo/NRPMInteractivity
      repository_branch     : python
    # modifications of bibtex reference style
    bibtex_default_style    : plain
    bibtex_reference_style  : label
    


# deactivate mybinder button and activate thebe button
launch_buttons:
  binderhub_url             : ""
  thebe                     : true