# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NRPM Digital handbook
author: Airbus Defence & Space
logo: Pictures/reliabilityspace_logo_vector.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# LaTeX settings
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

html:
  use_multitoc_numbering: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_navbar: |
        <div>
            By Matrisk & Airbus Defence & Space
            © Copyright 2022.
        </div>

# Information about where the book exists on the web
repository:
  url                       : https://github.com/paulremo/NRPMHandbook  # Online location of your book
  path_to_book              : 02_NRPMHandbook  # Optional path to your book, relative to the repository root
  branch                    : main 
 
 
# modifications of sphinx config
sphinx:
  config:
    # modifications of thebe config (change of the repo URL to the interactivity repo)
    thebe_config:
      repository_url        : https://github.com/paulremo/NRPMInteractivity
      repository_branch     : python


# deactivate mybinder button and activate thebe button
launch_buttons:
  binderhub_url             : ""
  thebe                     : true